name: AutoX.js Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          # 【修复】删掉 cache: 'gradle'，因为你根目录没这些文件

      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full

      - name: Download AutoX Build Engine
        run: |
          # 稳定获取 5.7.9 版本的打包模板
          curl -L -o autox_engine.zip https://github.com/kajizhang/AutoX/releases/download/v5.7.9/apk_common-v5.7.9.zip
          7z x autox_engine.zip -o./engine

      - name: Inject Project and Build
        run: |
          # 1. 将你的代码、图标、配置全部注入到引擎中
          mkdir -p ./engine/assets/project
          cp -r ./* ./engine/assets/project/
          
          # 2. 进入引擎目录开始编译
          cd engine
          chmod +x gradlew
          # 开始编译 Debug 版本 APK
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Rapid-Hunter-APK
          # 寻找编译生成的 APK 文件
          path: engine/app/build/outputs/apk/debug/*.apk